version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      #- pip install --upgrade --force-reinstall . awscli
      - pip install sagemaker
      - pip install stepfunctions
  
  build:
    commands:
      - python create-step-functions.py
      - echo "Create/Update of the SageMaker Pipeline and execution completed."
 
artifacts:
  files:
    - cloudformation_parameters.json
    